sudo: required

language: node_js

services:
  - docker

before_install:
  - docker build -t dhgreenstein/cloudchaos .
  - docker run -d -p 3000:3000 dhgreenstein/cloudchaos
  - docker ps -a

script:
  - curl http://127.0.0.1:3000