sudo: required
language: node_js

services:
  - docker

before_install:
  - docker build -t dhgreenstein/cloudchaos:latest .
  - docker run -d --net=host -p 127.0.0.1:3000:3000 dhgreenstein/cloudchaos:latest
  - sleep 15
  - docker ps -a

script:
  - curl localhost:3000
